spring.datasource.url=jdbc:mysql://bintzz5xzargoitudlfk-mysql.services.clever-cloud.com:3306/bintzz5xzargoitudlfk?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=ufk0s3hpq3dd3d2
spring.datasource.password=jZ0sK5mbbf5J05F1CNYF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true