spring.datasource.url=jdbc:mysql://bintzz5xzarqoitudlfk-mysql.services.clever-cloud.com:3306/bintzz5xzarqoitudlfk
spring.datasource.username=ufk0s35hpq3dd3d2
spring.datasource.password=jZ0sK5mbbf5J05F1CNYF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
